### ISSUE TITLE
The 1:1 zoom toolbar button should revert the zoom when hit repeatedly

### ISSUE THREAD

**Issue by Socialdarwinist** [teeuniverse/teeuniverse#140]
This is behavior users expect.

**Comment by necropotame** [comment]
It's a button, not a toggle. Do you know any program that works like this?

**Comment by Socialdarwinist** [comment]
I have dark remembrance of this being used in programs. Peradventure it is old-fashioned, but it is a convenient way to embosom additional functionality. It is somewhat disappointing otherwise, if one hit the button repeatedly and naught befall.
