### ISSUE TITLE
Question concerning the file make_assets_ninslash.cpp

### ISSUE THREAD

**Issue by lamppcat** [teeuniverse/teeuniverse#147]
teeuniverse/src/make_assets_ninslash.cpp

for(int i=11; i<192; i++)
		{
			CREATE_ZONEINDEX_NOUSE()
		}
		
		CREATE_ZONEINDEX_NOUSE()
		CREATE_ZONEINDEX_NOUSE()
		CREATE_ZONEINDEX_NOUSE()
		CREATE_ZONEINDEX_NOUSE()
		CREATE_ZONEINDEX_NOUSE()

**Comment by necropotame** [comment]
If you want to define something at the index 192, you must define previous indices. If you don't have anything to put inside, you can use this macro that create a new index with the booean "NotUsed" set to true.
