### ISSUE TITLE
Add space-key bind to show the tile selection menu

### ISSUE THREAD

**Issue by Zwelf** [teeuniverse/teeuniverse#167]
Currently you can only get the menu by right-clicking. it would be good, if you can select the tiles while pressing space like in the vanilla editor.
Additional an Escape-Bind would be great to close the tile selecting menu after a right click.

**Comment by necropotame** [comment]
Is it okay if spacebar is equivalent to right click? Open the palette or clean the stamp depending of it's state.
Escape seems fine for closing pop-ups in general :)

**Comment by Zwelf** [comment]
Yes I think that it would be okay.
