### ISSUE TITLE
Add a plus-Symbol to map-groups

### ISSUE THREAD

**Issue by Zwelf** [teeuniverse/teeuniverse#176]
Add a "+"-Symbol to mapgroups for adding new groups.
Something like there:
![plus](https://cloud.githubusercontent.com/assets/9964758/23835477/3e42c5ac-0768-11e7-832e-f15e6d29dc20.png)

**Comment by necropotame** [comment]
It's not enough if I add a right click menu in "Foreground Layers", "Zones", ... ?

**Comment by Zwelf** [comment]
Hm, I didn't through of this. I think right click on the menu points would be ok.
In my opinion a "+"-Symbol would fit better, but maybe there would be too much icons with the additionally plus Symbol.

**Comment by necropotame** [comment]
The problem if the + is on is that it could be interpreted as "hide/show elements inside the list". I will implement bthe right click. Maybe later I could add an entry in the list with the name "Add a layer" or something like this
