### ISSUE TITLE
Selecting a row with Shift key

### ISSUE THREAD

**Issue by EmeraldyDE** [teeuniverse/teeuniverse#183]
Selecting a row with holding shift, selecting an object then selecting some other object below it does not create a row. Is this Windows specific? I do not think so.

**Comment by necropotame** [comment]
What "row" is referring here?

**Comment by EmeraldyDE** [comment]
A row of items or objects.

**Comment by necropotame** [comment]
Ah ok. It's not implemented yet

**Comment by Socialdarwinist** [comment]
On Linux I select selectively with Ctrl, and put rows into my selection by Ctrl+Shift. Like when I have an array {1,2,3,4,5,6,7,8,9,10}, I click 2 to select it, then I ctrl+click 4 to have selected 2 and 4, then ctrl+shift+click 8 to have 2 and 4–8 selected.
It will be not so easy to implement it for objects in the map, but one expects it in every list.

**Comment by EmeraldyDE** [comment]
Why so much complication, duh?
Things can be easy.

**Comment by necropotame** [comment]
@Socialdarwinist Thanks for the precision about the combination of both options. it will be implemented like this

**Comment by EmeraldyDE** [comment]
Wow, I thought simplicity like this is good.
