### ISSUE TITLE
TUP sizes vary widely by manipulation of trifling things

### ISSUE THREAD

**Issue by Socialdarwinist** [teeuniverse/teeuniverse#192]
One can easily increase the size of a .TUP just by changing visibilities, zooming the map view out or putting it to a different place. In the following sample I have just made that, the content is identical short of these three parameters.

[infc_backwaters.tup.zip](https://github.com/teeuniverse/teeuniverse/files/887756/infc_backwaters.tup.zip)

**Comment by necropotame** [comment]
The size changes each time you save the package, even without modification, and during the same session.
